language: node_js
node_js:
- '0.12'
- 'iojs-v1'
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
before_script:
- npm prune
- curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
after_failure:
- python travis_after_all.py
- export $(cat .to_export_back)
before_deploy:
- rm -f travis_after_all.py .to_export_back
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
env:
  global:
    secure: MfWugwOoP3Yq5Iwn9/jFcLexMox0wx8FvyCPYT1UbviSiXne/h3mSLzbsyzurJC7ft4IyVCEuOmrxd9oAg43kdHHdkdAnws9Ct081RjUfvsASvz+w1F6QELNA5FXdf+vn4S+pmWDBIAc3E45LfpLNGLEbe57mPyJsz3F9Ke33UQ=
deploy:
  provider: npm
  email: jakob-npm@westhoffswelt.de
  skip_cleanup: true
  on:
    branch: master
    repo: jakobwesthoff/dependency.js
    condition: "$BUILD_LEADER$BUILD_AGGREGATE_STATUS = YESothers_succeeded"
  api_key:
    secure: J8l8Esmw2o2PtF3+Mv44YVHATXSXz8+AVMcLdSc4hC4w60nsCkx4JxvtXCn16YzE3JpsbA8Pv5hhNBXl2z88P4HheBjHmYkTCmJzuIzCu3Wy8vSPVjZQQPhe3BlKk1PLhEatjoYnXtAWO+fNt2uPEcnhSiVxE1Mz7+yBjDewQP8=
